name: Build Bot

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: "Target runtime"
        required: true
        default: "win-x64"
        type: choice
        options:
          - win-x64   # 64-bit Windows
          - win-x86   # 32-bit Windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -r ${{ github.event.inputs.runtime }} --self-contained false -o build

      - name: Create empty txt files
        run: |
          New-Item build/admins.txt -ItemType File
          New-Item build/voiced.txt -ItemType File
          New-Item build/config.ini -ItemType File
          New-Item build/messages.txt -ItemType File

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: MedalBot-Build
          path: build
